components:
    - core
    - enc-utf16
    - enc-base64
    - md5
    - sha1
    - sha256
    - hmac
    - pbkdf2
    - evpkdf
    - cipher-core
    - mode-cfb
    - mode-ctr
    - mode-ofb
    - mode-ecb
    - pad-ansix923
    - pad-iso10126
    - pad-iso97971
    - pad-zeropadding
    - pad-nopadding
    - aes
    - tripledes
    - rc4
    - rabbit

rollups:
    md5:    [core, md5]
    sha1:   [core, sha1]
    sha256: [core, sha256]

    hmac-md5:    [core, md5, hmac]
    hmac-sha1:   [core, sha1, hmac]
    hmac-sha256: [core, sha256, hmac]

    pbkdf2: [core, sha1, hmac, pbkdf2]

    aes:       [core, enc-base64, md5, evpkdf, cipher-core, aes]
    tripledes: [core, enc-base64, md5, evpkdf, cipher-core, tripledes]
    rc4:       [core, enc-base64, md5, evpkdf, cipher-core, rc4]
    rabbit:    [core, enc-base64, md5, evpkdf, cipher-core, rabbit]
